In [1]:
import pandas as pd
%matplotlib inline
import matplotlib.pyplot as plt
import numpy as np
from numpy import median
import seaborn as sns
import warnings
warnings.filterwarnings("ignore")

In [2]:
data2022 = pd.read_csv("Rendimiento por estudiante 2022.csv", sep=';')
data2022

,AGNO,RBD,DGV_RBD,NOM_RBD,COD_REG_RBD,NOM_REG_RBD_A,COD_PRO_RBD,COD_COM_RBD,NOM_COM_RBD,COD_DEPROV_RBD,...,COD_COM_ALU,NOM_COM_ALU,COD_RAMA,COD_SEC,COD_ESPE,PROM_GRAL,ASISTENCIA,SIT_FIN,SIT_FIN_R,COD_MEN
0,2022,1,9,LICEO POLITECNICO ARICA,15,AYP,151,15101,ARICA,151,...,15101,ARICA,400,410,41001,"6,6",98,P,P,0
1,2022,1,9,LICEO POLITECNICO ARICA,15,AYP,151,15101,ARICA,151,...,15101,ARICA,400,410,41001,0,0,Y,T,0
2,2022,1,9,LICEO POLITECNICO ARICA,15,AYP,151,15101,ARICA,151,...,15101,ARICA,400,410,41001,0,0,Y,Y,0
3,2022,1,9,LICEO POLITECNICO ARICA,15,AYP,151,15101,ARICA,151,...,15101,ARICA,400,410,41001,0,0,Y,T,0
4,2022,1,9,LICEO POLITECNICO ARICA,15,AYP,151,15101,ARICA,151,...,15101,ARICA,400,410,41001,0,0,Y,Y,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3405125,2022,42130,8,ESCUELA HOSPITALARIA PROVINCIA CORDILLERA PUEN...,13,RM,132,13201,PUENTE ALTO,136,...,13201,PUENTE ALTO,0,0,0,0,100,,,0
3405126,2022,42130,8,ESCUELA HOSPITALARIA PROVINCIA CORDILLERA PUEN...,13,RM,132,13201,PUENTE ALTO,136,...,13201,PUENTE ALTO,0,0,0,0,0,Y,T,0
3405127,2022,42130,8,ESCUELA HOSPITALARIA PROVINCIA CORDILLERA PUEN...,13,RM,132,13201,PUENTE ALTO,136,...,13122,PEÑALOLÉN,0,0,0,0,0,Y,T,0
3405128,2022,42130,8,ESCUELA HOSPITALARIA PROVINCIA CORDILLERA PUEN...,13,RM,132,13201,PUENTE ALTO,136,...,13112,LA PINTANA,0,0,0,0,0,Y,T,0
3405129,2022,42130,8,ESCUELA HOSPITALARIA PROVINCIA CORDILLERA PUEN...,13,RM,132,13201,PUENTE ALTO,136,...,13201,PUENTE ALTO,0,0,0,0,0,Y,T,0

In [3]:
data2021 = pd.read_csv("Rendimiento por estudiante 2021.csv", sep=';')
data2021

,AGNO,RBD,DGV_RBD,NOM_RBD,COD_REG_RBD,NOM_REG_RBD_A,COD_PRO_RBD,COD_COM_RBD,NOM_COM_RBD,COD_DEPROV_RBD,...,COD_COM_ALU,NOM_COM_ALU,COD_RAMA,COD_SEC,COD_ESPE,PROM_GRAL,ASISTENCIA,SIT_FIN,SIT_FIN_R,COD_MEN
0,2021,1,9,LICEO POLITECNICO ARICA,15,AYP,151,15101,ARICA,151,...,15101,ARICA,400,410,41001,"6,5",98,P,P,0
1,2021,1,9,LICEO POLITECNICO ARICA,15,AYP,151,15101,ARICA,151,...,15101,ARICA,400,410,41001,"6,5",98,P,P,0
2,2021,1,9,LICEO POLITECNICO ARICA,15,AYP,151,15101,ARICA,151,...,15101,ARICA,400,410,41001,"5,8",90,P,P,0
3,2021,1,9,LICEO POLITECNICO ARICA,15,AYP,151,15101,ARICA,151,...,15101,ARICA,400,410,41001,0,0,Y,Y,0
4,2021,1,9,LICEO POLITECNICO ARICA,15,AYP,151,15101,ARICA,151,...,1101,IQUIQUE,400,410,41001,"4,1",70,R,R,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3237038,2021,41955,9,ESCUELA HOSPITALARIA LOS ÁNGELES,8,BBIO,83,8301,LOS ÁNGELES,82,...,8110,TALCAHUANO,0,0,0,0,0,Y,Y,0
3237039,2021,41955,9,ESCUELA HOSPITALARIA LOS ÁNGELES,8,BBIO,83,8301,LOS ÁNGELES,82,...,13125,QUILICURA,0,0,0,"6,5",100,P,P,0
3237040,2021,41955,9,ESCUELA HOSPITALARIA LOS ÁNGELES,8,BBIO,83,8301,LOS ÁNGELES,82,...,8306,NACIMIENTO,0,0,0,5,100,P,P,0
3237041,2021,41955,9,ESCUELA HOSPITALARIA LOS ÁNGELES,8,BBIO,83,8301,LOS ÁNGELES,82,...,8301,LOS ÁNGELES,0,0,0,"6,6",100,P,P,0
3237042,2021,41955,9,ESCUELA HOSPITALARIA LOS ÁNGELES,8,BBIO,83,8301,LOS ÁNGELES,82,...,8313,YUMBEL,0,0,0,"6,6",100,P,P,0

In [4]:
data2020 = pd.read_csv("Rendimiento por estudiante 2020.csv", sep=';')
data2020

,AGNO,RBD,DGV_RBD,NOM_RBD,COD_REG_RBD,NOM_REG_RBD_A,COD_PRO_RBD,COD_COM_RBD,NOM_COM_RBD,COD_DEPROV_RBD,...,COD_COM_ALU,NOM_COM_ALU,COD_RAMA,COD_SEC,COD_ESPE,PROM_GRAL,ASISTENCIA,SIT_FIN,SIT_FIN_R,COD_MEN
0,2020,1,9,LICEO POLITECNICO ARICA,15,AYP,151,15101,ARICA,151,...,15101,ARICA,400,410,41001,"6,7",100,P,P,0
1,2020,1,9,LICEO POLITECNICO ARICA,15,AYP,151,15101,ARICA,151,...,15101,ARICA,400,410,41001,"5,5",100,P,P,0
2,2020,1,9,LICEO POLITECNICO ARICA,15,AYP,151,15101,ARICA,151,...,15101,ARICA,400,410,41001,0,0,Y,Y,0
3,2020,1,9,LICEO POLITECNICO ARICA,15,AYP,151,15101,ARICA,151,...,15101,ARICA,400,410,41001,"5,2",100,P,P,0
4,2020,1,9,LICEO POLITECNICO ARICA,15,AYP,151,15101,ARICA,151,...,15101,ARICA,400,410,41001,"4,9",100,P,P,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3164529,2020,41807,2,INSTITUTO DE ENSEÑANZA PRIMARIA PROFESOR PAULO...,13,RM,131,13130,SAN MIGUEL,131,...,13129,SAN JOAQUÍN,0,0,0,"6,8",100,P,P,0
3164530,2020,41807,2,INSTITUTO DE ENSEÑANZA PRIMARIA PROFESOR PAULO...,13,RM,131,13130,SAN MIGUEL,131,...,13121,PEDRO AGUIRRE CERDA,0,0,0,"6,9",100,P,P,0
3164531,2020,41807,2,INSTITUTO DE ENSEÑANZA PRIMARIA PROFESOR PAULO...,13,RM,131,13130,SAN MIGUEL,131,...,13130,SAN MIGUEL,0,0,0,7,100,P,P,0
3164532,2020,41807,2,INSTITUTO DE ENSEÑANZA PRIMARIA PROFESOR PAULO...,13,RM,131,13130,SAN MIGUEL,131,...,13131,SAN RAMÓN,0,0,0,"6,9",100,P,P,0
3164533,2020,41807,2,INSTITUTO DE ENSEÑANZA PRIMARIA PROFESOR PAULO...,13,RM,131,13130,SAN MIGUEL,131,...,13101,SANTIAGO,0,0,0,7,100,P,P,0

In [5]:
data2019 = pd.read_csv("Rendimiento por estudiante 2019..csv", sep=';')
data2019

,AGNO,RBD,DGV_RBD,NOM_RBD,COD_REG_RBD,NOM_REG_RBD_A,COD_PRO_RBD,COD_COM_RBD,NOM_COM_RBD,COD_DEPROV_RBD,...,COD_COM_ALU,NOM_COM_ALU,COD_RAMA,COD_SEC,COD_ESPE,PROM_GRAL,ASISTENCIA,SIT_FIN,SIT_FIN_R,COD_MEN
0,2019,1,9,LICEO POLITECNICO ARICA,15,AYP,151,15101,ARICA,151,...,15101,ARICA,400,410,41001,5,85,P,P,0
1,2019,1,9,LICEO POLITECNICO ARICA,15,AYP,151,15101,ARICA,151,...,15101,ARICA,400,410,41001,0,0,Y,Y,0
2,2019,1,9,LICEO POLITECNICO ARICA,15,AYP,151,15101,ARICA,151,...,15101,ARICA,400,410,41001,"4,9",89,R,R,0
3,2019,1,9,LICEO POLITECNICO ARICA,15,AYP,151,15101,ARICA,151,...,15101,ARICA,400,410,41001,0,0,Y,Y,0
4,2019,1,9,LICEO POLITECNICO ARICA,15,AYP,151,15101,ARICA,151,...,1107,ALTO HOSPICIO,400,410,41001,0,0,Y,T,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3328910,2019,41421,2,INSTITUTO PREMILITAR DE CHILE,13,RM,136,13604,PADRE HURTADO,135,...,13102,CERRILLOS,0,0,0,"6,1",100,P,P,0
3328911,2019,41421,2,INSTITUTO PREMILITAR DE CHILE,13,RM,136,13604,PADRE HURTADO,135,...,13119,MAIPÚ,0,0,0,"6,1",100,P,P,0
3328912,2019,41421,2,INSTITUTO PREMILITAR DE CHILE,13,RM,136,13604,PADRE HURTADO,135,...,13101,SANTIAGO,0,0,0,"6,1",100,P,P,0
3328913,2019,41421,2,INSTITUTO PREMILITAR DE CHILE,13,RM,136,13604,PADRE HURTADO,135,...,13117,LO PRADO,0,0,0,"6,2",100,P,P,0
3328914,2019,41421,2,INSTITUTO PREMILITAR DE CHILE,13,RM,136,13604,PADRE HURTADO,135,...,13201,PUENTE ALTO,0,0,0,"5,2",100,P,P,0

In [6]:
data2018 = pd.read_csv("Rendimiento por estudiante 2018.csv", sep=';')
data2018

,AGNO,RBD,DGV_RBD,NOM_RBD,COD_REG_RBD,NOM_REG_RBD_A,COD_PRO_RBD,COD_COM_RBD,NOM_COM_RBD,COD_DEPROV_RBD,...,COD_REG_ALU,COD_COM_ALU,NOM_COM_ALU,COD_RAMA,COD_SEC,COD_ESPE,PROM_GRAL,ASISTENCIA,SIT_FIN,SIT_FIN_R
0,2018,1,9,LICEO POLITECNICO ARICA,15,AYP,151,15101,ARICA,151,...,15,15101,ARICA,400,410,41001,0,0,Y,T
1,2018,1,9,LICEO POLITECNICO ARICA,15,AYP,151,15101,ARICA,151,...,15,15101,ARICA,400,410,41001,0,0,Y,Y
2,2018,1,9,LICEO POLITECNICO ARICA,15,AYP,151,15101,ARICA,151,...,15,15101,ARICA,400,410,41001,0,0,Y,T
3,2018,1,9,LICEO POLITECNICO ARICA,15,AYP,151,15101,ARICA,151,...,15,15101,ARICA,400,410,41001,"6,4",95,P,P
4,2018,1,9,LICEO POLITECNICO ARICA,15,AYP,151,15101,ARICA,151,...,15,15101,ARICA,400,410,41001,0,0,Y,Y
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3293745,2018,41063,2,AULA HOSPITALARIA DE ARICA,15,AYP,151,15101,ARICA,151,...,15,15101,ARICA,0,0,0,"6,3",100,P,P
3293746,2018,41063,2,AULA HOSPITALARIA DE ARICA,15,AYP,151,15101,ARICA,151,...,15,15101,ARICA,0,0,0,"6,1",100,P,P
3293747,2018,41063,2,AULA HOSPITALARIA DE ARICA,15,AYP,151,15101,ARICA,151,...,15,15101,ARICA,0,0,0,"6,3",100,P,P
3293748,2018,41063,2,AULA HOSPITALARIA DE ARICA,15,AYP,151,15101,ARICA,151,...,15,15101,ARICA,0,0,0,"5,9",100,P,P
3293749,2018,41063,2,AULA HOSPITALARIA DE ARICA,15,AYP,151,15101,ARICA,151,...,3,3301,VALLENAR,0,0,0,"5,4",100,P,P

In [7]:
data2017 = pd.read_csv("Rendimiento por estudiante 2017.csv", sep=';')
data2017

,agno,rbd,dgv_rbd,nom_rbd,cod_reg_rbd,cod_pro_rbd,cod_com_rbd,nom_com_rbd,cod_deprov_rbd,nom_deprov_rbd,...,cod_reg_alu,cod_com_alu,nom_com_alu,cod_rama,cod_sec,cod_espe,prom_gral,asistencia,sit_fin,sit_fin_r
0,2017,1,9,LICEO POLITECNICO ARICA,15,151,15101,ARICA,151,ARICA,...,15,15101,ARICA,400,410,41001,0,0,Y,Y
1,2017,1,9,LICEO POLITECNICO ARICA,15,151,15101,ARICA,151,ARICA,...,15,15101,ARICA,400,410,41001,0,0,Y,T
2,2017,1,9,LICEO POLITECNICO ARICA,15,151,15101,ARICA,151,ARICA,...,15,15101,ARICA,400,410,41001,0,0,Y,Y
3,2017,1,9,LICEO POLITECNICO ARICA,15,151,15101,ARICA,151,ARICA,...,15,15101,ARICA,400,410,41001,6,85,P,P
4,2017,1,9,LICEO POLITECNICO ARICA,15,151,15101,ARICA,151,ARICA,...,15,15101,ARICA,400,410,41001,"6,1",100,P,P
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3246819,2017,40459,4,CENTRO EDUCACIONAL ALBORADA,10,102,10202,ANCUD,102,CHILOE,...,10,10202,ANCUD,0,0,0,"6,6",98,P,P
3246820,2017,40459,4,CENTRO EDUCACIONAL ALBORADA,10,102,10202,ANCUD,102,CHILOE,...,10,10202,ANCUD,0,0,0,5,97,P,P
3246821,2017,40459,4,CENTRO EDUCACIONAL ALBORADA,10,102,10202,ANCUD,102,CHILOE,...,10,10202,ANCUD,0,0,0,"4,5",96,P,P
3246822,2017,40459,4,CENTRO EDUCACIONAL ALBORADA,10,102,10202,ANCUD,102,CHILOE,...,10,10202,ANCUD,0,0,0,"5,1",77,P,P
3246823,2017,40459,4,CENTRO EDUCACIONAL ALBORADA,10,102,10202,ANCUD,102,CHILOE,...,10,10201,CASTRO,0,0,0,"4,7",87,P,P

In [8]:
data2016 = pd.read_csv("Rendimiento por estudiante 2016.csv", sep=';')
data2016

,agno,rbd,dgv_rbd,nom_rbd,cod_reg_rbd,cod_pro_rbd,cod_com_rbd,nom_com_rbd,cod_deprov_rbd,nom_deprov_rbd,...,cod_reg_alu,cod_com_alu,nom_com_alu,cod_rama,cod_sec,cod_espe,prom_gral,asistencia,sit_fin,sit_fin_r
0,2016,1,9,LICEO POLITECNICO ARICA,15,151,15101,ARICA,151,ARICA,...,15,15101,ARICA,400,410,41001,0,0,Y,Y
1,2016,1,9,LICEO POLITECNICO ARICA,15,151,15101,ARICA,151,ARICA,...,2,2101,ANTOFAGASTA,400,410,41001,0,0,Y,T
2,2016,1,9,LICEO POLITECNICO ARICA,15,151,15101,ARICA,151,ARICA,...,15,15101,ARICA,400,410,41001,"6,1",85,P,P
3,2016,1,9,LICEO POLITECNICO ARICA,15,151,15101,ARICA,151,ARICA,...,15,15101,ARICA,400,410,41001,0,0,Y,Y
4,2016,1,9,LICEO POLITECNICO ARICA,15,151,15101,ARICA,151,ARICA,...,15,15101,ARICA,400,410,41001,0,0,Y,T
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3226938,2016,40459,4,CENTRO EDUCACIONAL ALBORADA,10,102,10202,ANCUD,102,CHILOE,...,10,10202,ANCUD,0,0,0,"5,3",94,P,P
3226939,2016,40459,4,CENTRO EDUCACIONAL ALBORADA,10,102,10202,ANCUD,102,CHILOE,...,10,10202,ANCUD,0,0,0,"5,2",94,P,P
3226940,2016,40459,4,CENTRO EDUCACIONAL ALBORADA,10,102,10202,ANCUD,102,CHILOE,...,10,10202,ANCUD,0,0,0,"6,5",95,P,P
3226941,2016,40459,4,CENTRO EDUCACIONAL ALBORADA,10,102,10202,ANCUD,102,CHILOE,...,10,10202,ANCUD,0,0,0,"4,9",38,P,P
3226942,2016,40459,4,CENTRO EDUCACIONAL ALBORADA,10,102,10202,ANCUD,102,CHILOE,...,10,10202,ANCUD,0,0,0,"5,5",93,P,P

In [9]:
data2015 = pd.read_csv("Rendimiento por estudiante 2015.csv", sep=';', encoding='ISO-8859-1')
data2015

,AGNO,RBD,DGV_RBD,NOM_RBD,COD_REG_RBD,COD_PRO_RBD,COD_COM_RBD,NOM_COM_RBD,COD_DEPROV_RBD,NOM_DEPROV_RBD,...,COD_REG_ALU,COD_COM_ALU,NOM_COM_ALU,COD_RAMA,COD_SEC,COD_ESPE,PROM_GRAL,ASISTENCIA,SIT_FIN,SIT_FIN_R
0,2015,1,9,LICEO POLITECNICO ARICA,15,151,15101,ARICA,151,ARICA,...,15,15101,ARICA,400,410,41001,"5,3",85,P,P
1,2015,1,9,LICEO POLITECNICO ARICA,15,151,15101,ARICA,151,ARICA,...,15,15101,ARICA,400,410,41001,"5,2",85,P,P
2,2015,1,9,LICEO POLITECNICO ARICA,15,151,15101,ARICA,151,ARICA,...,15,15101,ARICA,400,410,41001,0,0,Y,T
3,2015,1,9,LICEO POLITECNICO ARICA,15,151,15101,ARICA,151,ARICA,...,15,15101,ARICA,400,410,41001,0,0,Y,Y
4,2015,1,9,LICEO POLITECNICO ARICA,15,151,15101,ARICA,151,ARICA,...,15,15101,ARICA,400,410,41001,0,0,Y,Y
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3238581,2015,40459,4,CENTRO EDUCACIONAL ALBORADA,10,102,10202,ANCUD,102,CHILOE,...,10,10202,ANCUD,0,0,0,"4,8",94,P,P
3238582,2015,40459,4,CENTRO EDUCACIONAL ALBORADA,10,102,10202,ANCUD,102,CHILOE,...,10,10202,ANCUD,0,0,0,"5,4",97,P,P
3238583,2015,40459,4,CENTRO EDUCACIONAL ALBORADA,10,102,10202,ANCUD,102,CHILOE,...,10,10202,ANCUD,0,0,0,"6,4",96,P,P
3238584,2015,40459,4,CENTRO EDUCACIONAL ALBORADA,10,102,10202,ANCUD,102,CHILOE,...,10,10202,ANCUD,0,0,0,"5,6",71,P,P
3238585,2015,40459,4,CENTRO EDUCACIONAL ALBORADA,10,102,10202,ANCUD,102,CHILOE,...,10,10202,ANCUD,0,0,0,"5,3",90,P,P

In [10]:
data2014 = pd.read_csv("Rendimiento por estudiante 2014.csv", sep=';')
data2014

,AGNO,RBD,DGV_RBD,NOM_RBD,COD_REG_RBD,COD_PRO_RBD,COD_COM_RBD,NOM_COM_RBD,COD_DEPE,COD_DEPE2,...,COD_REG_ALU,COD_COM_ALU,NOM_COM_ALU,COD_RAMA,COD_SEC,COD_ESPE,PROM_GRAL,ASISTENCIA,SIT_FIN,SIT_FIN_R
0,2014,1,9,LICEO POLITECNICO ARICA,15,151,15101,ARICA,2,1,...,15,15101,ARICA,400,410,41001,6,95,P,P
1,2014,1,9,LICEO POLITECNICO ARICA,15,151,15101,ARICA,2,1,...,15,15101,ARICA,400,410,41001,0,0,Y,Y
2,2014,1,9,LICEO POLITECNICO ARICA,15,151,15101,ARICA,2,1,...,15,15101,ARICA,400,410,41001,0,0,Y,Y
3,2014,1,9,LICEO POLITECNICO ARICA,15,151,15101,ARICA,2,1,...,13,13401,SAN BERNARDO,400,410,41001,0,0,Y,Y
4,2014,1,9,LICEO POLITECNICO ARICA,15,151,15101,ARICA,2,1,...,15,15101,ARICA,400,410,41001,0,0,Y,Y
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3227529,2014,40459,4,CENTRO EDUCACIONAL ALBORADA,10,102,10202,ANCUD,3,2,...,10,10202,ANCUD,0,0,0,"5,2",84,P,P
3227530,2014,40459,4,CENTRO EDUCACIONAL ALBORADA,10,102,10202,ANCUD,3,2,...,10,10202,ANCUD,0,0,0,"5,1",91,P,P
3227531,2014,40459,4,CENTRO EDUCACIONAL ALBORADA,10,102,10202,ANCUD,3,2,...,10,10202,ANCUD,0,0,0,"4,7",92,P,P
3227532,2014,40459,4,CENTRO EDUCACIONAL ALBORADA,10,102,10202,ANCUD,3,2,...,14,14106,MARIQUINA,0,0,0,0,0,Y,T
3227533,2014,40459,4,CENTRO EDUCACIONAL ALBORADA,10,102,10202,ANCUD,3,2,...,10,10202,ANCUD,0,0,0,"5,3",88,P,P

In [11]:
data2013 = pd.read_csv("Rendimiento por estudiante 2013.csv", sep=';')
data2013

,AGNO,RBD,DGV_RBD,NOM_RBD,COD_REG_RBD,COD_PRO_RBD,COD_COM_RBD,NOM_COM_RBD,COD_DEPE,RURAL_RBD,...,COD_REG_ALU,COD_COM_ALU,NOM_COM_ALU,COD_RAMA,COD_SEC,COD_ESPE,PROM_GRAL,ASISTENCIA,SIT_FIN,SIT_FIN_R
0,2013,1,9,LICEO POLITECNICO ARICA,15,151,15101,ARICA,2,0,...,15,15101,ARICA,400,410,41001,0,0,Y,Y
1,2013,1,9,LICEO POLITECNICO ARICA,15,151,15101,ARICA,2,0,...,15,15101,ARICA,400,410,41001,0,0,Y,T
2,2013,1,9,LICEO POLITECNICO ARICA,15,151,15101,ARICA,2,0,...,15,15101,ARICA,400,410,41001,"4,2",90,P,P
3,2013,1,9,LICEO POLITECNICO ARICA,15,151,15101,ARICA,2,0,...,15,15101,ARICA,400,410,41001,"5,9",98,P,P
4,2013,1,9,LICEO POLITECNICO ARICA,15,151,15101,ARICA,2,0,...,15,15101,ARICA,400,410,41001,0,0,Y,Y
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3255513,2013,40459,4,CENTRO EDUCACIONAL ALBORADA,10,102,10202,ANCUD,3,0,...,10,10202,ANCUD,0,0,0,"6,1",95,P,P
3255514,2013,40459,4,CENTRO EDUCACIONAL ALBORADA,10,102,10202,ANCUD,3,0,...,10,10202,ANCUD,0,0,0,"4,7",89,P,P
3255515,2013,40459,4,CENTRO EDUCACIONAL ALBORADA,10,102,10202,ANCUD,3,0,...,10,10202,ANCUD,0,0,0,"4,8",97,P,P
3255516,2013,40459,4,CENTRO EDUCACIONAL ALBORADA,10,102,10202,ANCUD,3,0,...,10,10202,ANCUD,0,0,0,"5,4",96,P,P
3255517,2013,40459,4,CENTRO EDUCACIONAL ALBORADA,10,102,10202,ANCUD,3,0,...,10,10202,ANCUD,0,0,0,"5,2",91,P,P

In [12]:
data2012 = pd.read_csv("Rendimiento por estudiante 2012.csv", sep=';')
data2012

,agno,rbd,dgv_rbd,nom_rbd,cod_reg_rbd,cod_com_rbd,nom_com_rbd,cod_depe,rural_rbd,cod_ense,...,fec_nac_alu,int_alu,cod_com_alu,nom_com_alu,cod_sec,cod_espe,prom_gral,asistencia,sit_fin,sit_fin_r
0,2012,1,9,LICEO POLITECNICO ARICA,15,15101,ARICA,2,0,463,...,19720703,0,15101,ARICA,410,41001,"5,3",89,P,P
1,2012,1,9,LICEO POLITECNICO ARICA,15,15101,ARICA,2,0,463,...,19600108,0,15101,ARICA,410,41001,"6,2",98,P,P
2,2012,1,9,LICEO POLITECNICO ARICA,15,15101,ARICA,2,0,463,...,19700605,0,15101,ARICA,410,41001,"6,3",97,P,P
3,2012,1,9,LICEO POLITECNICO ARICA,15,15101,ARICA,2,0,463,...,19731012,0,15101,ARICA,410,41001,"5,7",90,P,P
4,2012,1,9,LICEO POLITECNICO ARICA,15,15101,ARICA,2,0,463,...,19791001,0,15101,ARICA,410,41001,6,99,P,P
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3308472,2012,40459,4,CENTRO EDUCACIONAL ALBORADA,10,10202,ANCUD,3,0,110,...,20030428,0,10202,ANCUD,0,0,"5,3",99,P,P
3308473,2012,40459,4,CENTRO EDUCACIONAL ALBORADA,10,10202,ANCUD,3,0,110,...,20030603,0,10202,ANCUD,0,0,"6,3",92,P,P
3308474,2012,40459,4,CENTRO EDUCACIONAL ALBORADA,10,10202,ANCUD,3,0,110,...,20030608,0,10202,ANCUD,0,0,"5,6",97,P,P
3308475,2012,40459,4,CENTRO EDUCACIONAL ALBORADA,10,10202,ANCUD,3,0,110,...,20020813,0,10202,ANCUD,0,0,"4,4",97,R,R
3308476,2012,40459,4,CENTRO EDUCACIONAL ALBORADA,10,10202,ANCUD,3,0,110,...,20020916,0,10202,ANCUD,0,0,0,0,Y,T

In [13]:
data2011 = pd.read_csv("Rendimiento por estudiante 2011.csv", sep=';')
data2011

,AGNO,RBD,DGV_RBD,NOM_RBD,COD_REG_RBD,COD_COM_RBD,NOM_COM_RBD,COD_DEPE,RURAL_RBD,COD_ENSE,...,INT_ALU,COD_COM_ALU,NOM_COM_ALU,COD_SEC,COD_ESPE,FEC_ING_ALU,PROM_GRAL,ASISTENCIA,SIT_FIN,SIT_FIN_R
0,2011,1,9,LICEO POLITECNICO ARICA,15,15101,ARICA,2,0,610,...,0,15101,ARICA,620,62004,20110215,"5,3",85,P,P
1,2011,1,9,LICEO POLITECNICO ARICA,15,15101,ARICA,2,0,563,...,0,15101,ARICA,0,0,20110525,"4,9",85,P,P
2,2011,1,9,LICEO POLITECNICO ARICA,15,15101,ARICA,2,0,510,...,0,15101,ARICA,520,52009,20110215,"5,4",85,P,P
3,2011,1,9,LICEO POLITECNICO ARICA,15,15101,ARICA,2,0,610,...,0,15101,ARICA,610,61002,20110215,"5,2",93,P,P
4,2011,1,9,LICEO POLITECNICO ARICA,15,15101,ARICA,2,0,610,...,0,15101,ARICA,620,62004,20110215,"4,5",85,R,R
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3326741,2011,40436,5,COLEGIO AVANT GARDE,5,5801,QUILPUÉ,4,0,110,...,0,5101,VALPARAÍSO,,,20110330,5,72,P,P
3326742,2011,40436,5,COLEGIO AVANT GARDE,5,5801,QUILPUÉ,4,0,110,...,0,5801,QUILPUÉ,,,20110303,"5,6",91,P,P
3326743,2011,40436,5,COLEGIO AVANT GARDE,5,5801,QUILPUÉ,4,0,310,...,0,5109,VIÑA DEL MAR,,,20110519,"5,5",88,P,P
3326744,2011,40436,5,COLEGIO AVANT GARDE,5,5801,QUILPUÉ,4,0,310,...,0,5804,VILLA ALEMANA,,,20110303,"5,3",90,P,P
3326745,2011,40436,5,COLEGIO AVANT GARDE,5,5801,QUILPUÉ,4,0,110,...,0,5801,QUILPUÉ,,,20110303,"5,5",93,P,P

In [14]:
data2010 = pd.read_csv("Rendimiento por estudiante 2010.csv", sep=';')
data2010

,AGNO,RBD,DGV_RBD,NOM_RBD,COD_DEPE,COD_REG_RBD,COD_COM_RBD,NOM_COM_RBD,RURAL_RBD,COD_ENSE,...,FEC_NAC_ALU,INT_ALU,COD_COM_ALU,NOM_COM_ALU,COD_SEC,COD_ESPE,PROM_GRAL,ASISTENCIA,SIT_FIN,SIT_FIN_R
0,2010,1,9,LICEO POLITECNICO ARICA,2,15,15101,ARICA,0,610,...,19890404,0,15101,ARICA,610,61002,"5,7",92,P,P
1,2010,1,9,LICEO POLITECNICO ARICA,2,15,15101,ARICA,0,610,...,19920701,0,15101,ARICA,620,62004,"5,8",100,P,P
2,2010,1,9,LICEO POLITECNICO ARICA,2,15,15101,ARICA,0,510,...,19960128,0,15101,ARICA,0,0,0,0,Y,T
3,2010,1,9,LICEO POLITECNICO ARICA,2,15,15101,ARICA,0,510,...,19920330,0,15101,ARICA,520,52009,"5,2",91,P,P
4,2010,1,9,LICEO POLITECNICO ARICA,2,15,15101,ARICA,0,510,...,19941230,0,15101,ARICA,0,0,"5,1",95,P,P
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3335820,2010,40352,0,LICEO TEC.PROFESIONAL PEDRO AGUIRRE CERDA,2,5,5302,CALLE LARGA,0,310,...,19950516,0,5301,LOS ANDES,,,5,89,P,P
3335821,2010,40352,0,LICEO TEC.PROFESIONAL PEDRO AGUIRRE CERDA,2,5,5302,CALLE LARGA,0,310,...,19950930,0,5303,RINCONADA,,,"5,4",89,P,P
3335822,2010,40352,0,LICEO TEC.PROFESIONAL PEDRO AGUIRRE CERDA,2,5,5302,CALLE LARGA,0,310,...,19951113,0,5302,CALLE LARGA,,,"5,5",85,P,P
3335823,2010,40352,0,LICEO TEC.PROFESIONAL PEDRO AGUIRRE CERDA,2,5,5302,CALLE LARGA,0,310,...,19940709,0,5302,CALLE LARGA,,,"5,8",90,P,P
3335824,2010,40352,0,LICEO TEC.PROFESIONAL PEDRO AGUIRRE CERDA,2,5,5302,CALLE LARGA,0,310,...,19921029,0,5301,LOS ANDES,,,5,92,P,P

In [15]:
data2009 = pd.read_csv("Rendimiento por estudiante 2009.csv", sep=';')
data2009

,AGNO,RBD,DGV_RBD,NOM_RBD,LET_RBD,NUM_RBD,COD_REG_RBD,COD_COM_RBD,NOM_COM_RBD,COD_DEPE,...,FEC_NAC_ALU,INT_ALU,COD_COM_ALU,NOM_COM_ALU,COD_SEC,COD_ESPE,PROM_GRAL,ASISTENCIA,SIT_FIN,SIT_FIN_R
0,2009,1,9,LICEO POLITECNICO ARICA,A,2,15,15101,ARICA,2,...,19890404,0,15101,ARICA,610,61002,"5,9",93,P,P
1,2009,1,9,LICEO POLITECNICO ARICA,A,2,15,15101,ARICA,2,...,19920701,0,15101,ARICA,0,0,"5,2",86,P,P
2,2009,1,9,LICEO POLITECNICO ARICA,A,2,15,15101,ARICA,2,...,19920330,0,15101,ARICA,0,0,"4,8",92,P,P
3,2009,1,9,LICEO POLITECNICO ARICA,A,2,15,15101,ARICA,2,...,19941230,0,15101,ARICA,0,0,"5,2",98,P,P
4,2009,1,9,LICEO POLITECNICO ARICA,A,2,15,15101,ARICA,2,...,19940316,0,15101,ARICA,0,0,"5,8",99,P,P
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3326570,2009,40219,2,COLEGIO SAGRADA FAMILIA,.,0,6,6104,COLTAUCO,3,...,20010730,0,6104,COLTAUCO,,,"4,9",86,P,P
3326571,2009,40219,2,COLEGIO SAGRADA FAMILIA,.,0,6,6104,COLTAUCO,3,...,20020429,0,6104,COLTAUCO,,,"6,8",97,P,P
3326572,2009,40219,2,COLEGIO SAGRADA FAMILIA,.,0,6,6104,COLTAUCO,3,...,20030330,0,6104,COLTAUCO,,,"5,6",100,P,P
3326573,2009,40219,2,COLEGIO SAGRADA FAMILIA,.,0,6,6104,COLTAUCO,3,...,20020820,0,6104,COLTAUCO,,,"6,8",91,P,P
3326574,2009,40219,2,COLEGIO SAGRADA FAMILIA,.,0,6,6104,COLTAUCO,3,...,20010717,0,6104,COLTAUCO,,,"5,3",95,P,P

In [16]:
data2008 = pd.read_csv("Rendimiento por estudiante 2008.csv", sep=';')
data2008

,AGNO,RBD,DGV_RBD,NOM_RBD,LET_RBD,NUM_RBD,COD_REG_RBD,COD_COM_RBD,NOM_COM_RBD,COD_DEPE,...,FEC_NAC_ALU,INT_ALU,COD_COM_ALU,NOM_COM_ALU,COD_SEC,COD_ESPE,PROM_GRAL,ASISTENCIA,SIT_FIN,SIT_FIN_R
0,2008,1,9,LICEO POLITECNICO ARICA,A,2,15,15101,ARICA,2,...,19890404,0,15101,ARICA,0,0,"4,7",86,P,P
1,2008,1,9,LICEO POLITECNICO ARICA,A,2,15,15101,ARICA,2,...,19920701,0,15101,ARICA,0,0,"5,2",90,P,P
2,2008,1,9,LICEO POLITECNICO ARICA,A,2,15,15101,ARICA,2,...,19920303,0,15101,ARICA,0,0,5,85,P,P
3,2008,1,9,LICEO POLITECNICO ARICA,A,2,15,15101,ARICA,2,...,19900125,0,15101,ARICA,,,0,0,Y,Y
4,2008,1,9,LICEO POLITECNICO ARICA,A,2,15,15101,ARICA,2,...,19820607,0,15101,ARICA,620,62004,"5,8",97,P,P
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3356251,2008,40080,7,LICEO FERMIN DEL REAL CASTILLO,.,0,6,6302,CHEPICA,2,...,19890417,0,6302,CHEPICA,,,6,100,P,P
3356252,2008,40080,7,LICEO FERMIN DEL REAL CASTILLO,.,0,6,6302,CHEPICA,2,...,19940519,0,6302,CHEPICA,,,"5,6",99,P,P
3356253,2008,40080,7,LICEO FERMIN DEL REAL CASTILLO,.,0,6,6302,CHEPICA,2,...,19920317,0,6302,CHEPICA,,,"6,3",100,P,P
3356254,2008,40080,7,LICEO FERMIN DEL REAL CASTILLO,.,0,6,6302,CHEPICA,2,...,19940503,0,6302,CHEPICA,,,"4,4",99,P,P
3356255,2008,40080,7,LICEO FERMIN DEL REAL CASTILLO,.,0,6,6302,CHEPICA,2,...,19930910,0,6302,CHEPICA,,,"6,4",98,P,P

In [17]:
data2007 = pd.read_csv("Rendimiento por estudiante 2007.csv", sep=';')
data2007

,AGNO,RBD,DGV_RBD,NOM_RBD,LET_RBD,NUM_RBD,COD_REG_RBD,COD_COM_RBD,NOM_COM_RBD,COD_DEPE,...,FEC_NAC_ALU,INT_ALU,COD_COM_ALU,NOM_COM_ALU,COD_SEC,COD_ESPE,PROM_GRAL,ASISTENCIA,SIT_FIN,SIT_FIN_R
0,2007,1,9,LICEO POLITECNICO ARICA,A,2,15,15101,ARICA,2,...,19890404,0,15101,ARICA,0,0,"4,8",86,P,P
1,2007,1,9,LICEO POLITECNICO ARICA,A,2,15,15101,ARICA,2,...,19900511,0,15101,ARICA,,,"3,1",80,R,R
2,2007,1,9,LICEO POLITECNICO ARICA,A,2,15,15101,ARICA,2,...,19900125,0,15101,ARICA,,,"3,2",80,R,R
3,2007,1,9,LICEO POLITECNICO ARICA,A,2,15,15101,ARICA,2,...,19820607,0,15101,ARICA,,,"6,4",98,P,P
4,2007,1,9,LICEO POLITECNICO ARICA,A,2,15,15101,ARICA,2,...,19891120,0,15101,ARICA,510,51001,"3,9",45,R,R
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3413105,2007,26305,2,COLEGIO MONTAHUE,.,0,13,13122,PENALOLEN,4,...,19930725,0,13122,PEÑALOLÉN,,,"6,5",94,P,P
3413106,2007,26305,2,COLEGIO MONTAHUE,.,0,13,13122,PENALOLEN,4,...,19960704,0,13122,PEÑALOLÉN,,,"5,4",92,P,P
3413107,2007,26305,2,COLEGIO MONTAHUE,.,0,13,13122,PENALOLEN,4,...,19940103,0,13113,LA REINA,,,"5,6",98,P,P
3413108,2007,26305,2,COLEGIO MONTAHUE,.,0,13,13122,PENALOLEN,4,...,19921111,0,13119,MAIPÚ,,,0,0,Y,Y
3413109,2007,26305,2,COLEGIO MONTAHUE,.,0,13,13122,PENALOLEN,4,...,19890708,0,13122,PEÑALOLÉN,,,5,84,P,P

In [18]:
data2006 = pd.read_csv("Rendimiento por estudiante 2006.csv", sep=';')
data2006

,AGNO,RBD,DGV_RBD,NOM_RBD,LET_RBD,NUM_RBD,COD_REG_RBD,COD_COM_RBD,NOM_COM_RBD,COD_DEPE,...,FEC_NAC_ALU,INT_ALU,COD_COM_ALU,NOM_COM_ALU,COD_SEC,COD_ESPE,PROM_GRAL,ASISTENCIA,SIT_FIN,SIT_FIN_R
0,2006,1,9,LICEO POLITECNICO ARICA,A,2,1,1201,ARICA,2,...,19820607,0,1201,ARICA,0,0,6,99,P,P
1,2006,1,9,LICEO POLITECNICO ARICA,A,2,1,1201,ARICA,2,...,19781014,0,1201,ARICA,0,0,0,0,Y,Y
2,2006,1,9,LICEO POLITECNICO ARICA,A,2,1,1201,ARICA,2,...,19891120,0,1201,ARICA,0,0,5,89,P,P
3,2006,1,9,LICEO POLITECNICO ARICA,A,2,1,1201,ARICA,2,...,19861020,0,1201,ARICA,610,61002,"5,5",97,P,P
4,2006,1,9,LICEO POLITECNICO ARICA,A,2,1,1201,ARICA,2,...,19900227,0,1201,ARICA,,,0,0,Y,T
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3465579,2006,26173,4,ESCUELA BASICA ALTAIR DE BATUCO,,2152,13,13302,LAMPA,3,...,19990206,0,13302,LAMPA,,,"6,9",97,P,P
3465580,2006,26173,4,ESCUELA BASICA ALTAIR DE BATUCO,,2152,13,13302,LAMPA,3,...,19981203,0,13302,LAMPA,,,"6,4",98,P,P
3465581,2006,26173,4,ESCUELA BASICA ALTAIR DE BATUCO,,2152,13,13302,LAMPA,3,...,20000520,0,13302,LAMPA,,,0,0,Y,T
3465582,2006,26173,4,ESCUELA BASICA ALTAIR DE BATUCO,,2152,13,13302,LAMPA,3,...,19990217,0,13302,LAMPA,,,"5,6",99,P,P
3465583,2006,26173,4,ESCUELA BASICA ALTAIR DE BATUCO,,2152,13,13302,LAMPA,3,...,19981104,0,11201,AYSEN,,,"6,1",96,P,P

In [19]:
data2005 = pd.read_csv("Rendimiento por estudiante 2005.csv", sep=';')
data2005

,AGNO,RBD,DGV_RBD,NOM_RBD,LET_RBD,NUM_RBD,COD_REG_RBD,COD_COM_RBD,NOM_COM_RBD,COD_DEPE,...,FEC_NAC_ALU,INT_ALU,COD_COM_ALU,NOM_COM_ALU,COD_SEC,COD_ESPE,PROM_GRAL,ASISTENCIA,SIT_FIN,SIT_FIN_R
0,2005,1,9,LICEO POLITECNICO ARICA,A,2,1,1201,ARICA,2,...,19880523,0,1201,ARICA,530,53015,"4,6",94,P,P
1,2005,1,9,LICEO POLITECNICO ARICA,A,2,1,1201,ARICA,2,...,19890616,0,1201,ARICA,,,0,0,Y,Y
2,2005,1,9,LICEO POLITECNICO ARICA,A,2,1,1201,ARICA,2,...,19630422,0,1201,ARICA,,,"4,6",75,R,R
3,2005,1,9,LICEO POLITECNICO ARICA,A,2,1,1201,ARICA,2,...,19820607,0,1201,ARICA,0,0,"4,8",70,R,R
4,2005,1,9,LICEO POLITECNICO ARICA,A,2,1,1201,ARICA,2,...,19880523,0,1201,ARICA,620,62004,"6,5",90,P,P
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3506402,2005,26046,0,ESCUELA BASICA MANQUECURA DE LOS VALLES,,2090,13,13124,PUDAHUEL,4,...,19981201,0,13124,PUDAHUEL,,,"6,5",97,P,P
3506403,2005,26046,0,ESCUELA BASICA MANQUECURA DE LOS VALLES,,2090,13,13124,PUDAHUEL,4,...,19960607,0,13124,PUDAHUEL,,,"6,1",100,P,P
3506404,2005,26046,0,ESCUELA BASICA MANQUECURA DE LOS VALLES,,2090,13,13124,PUDAHUEL,4,...,19960304,0,13124,PUDAHUEL,,,6,91,P,P
3506405,2005,26046,0,ESCUELA BASICA MANQUECURA DE LOS VALLES,,2090,13,13124,PUDAHUEL,4,...,19940516,0,13124,PUDAHUEL,,,"6,8",92,P,P
3506406,2005,26046,0,ESCUELA BASICA MANQUECURA DE LOS VALLES,,2090,13,13124,PUDAHUEL,4,...,19951119,0,13124,PUDAHUEL,,,"6,1",97,P,P

In [20]:
data2004 = pd.read_csv("Rendimiento por estudiante 2004.csv", sep=';')
data2004

,AGNO,RBD,DGV_RBD,NOM_RBD,LET_RBD,NUM_RBD,COD_REG_RBD,COD_COM_RBD,NOM_COM_RBD,COD_DEPE,...,FEC_NAC_ALU,INT_ALU,COD_COM_ALU,NOM_COM_ALU,COD_SEC,COD_ESPE,PROM_GRAL,ASISTENCIA,SIT_FIN,SIT_FIN_R
0,2004,1,9,LICEO POLITECNICO ARICA,A,2,1,1201,ARICA,2,...,19871124,0,1201,ARICA,,,"5,5",85,P,P
1,2004,1,9,LICEO POLITECNICO ARICA,A,2,1,1201,ARICA,2,...,19880523,0,1201,ARICA,530,53015,5,98,P,P
2,2004,1,9,LICEO POLITECNICO ARICA,A,2,1,1201,ARICA,2,...,19860323,0,1201,ARICA,530,53015,"5,3",87,P,P
3,2004,1,9,LICEO POLITECNICO ARICA,A,2,1,1201,ARICA,2,...,19861106,0,1201,ARICA,0,0,6,93,P,P
4,2004,1,9,LICEO POLITECNICO ARICA,A,2,1,1201,ARICA,2,...,19870102,0,1201,ARICA,520,52010,"6,2",99,P,P
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3515833,2004,25958,4,ESCUELA BASICA MIRASOL DE SANTIAGO,,2047,13,13101,SANTIAGO,4,...,19970725,0,13101,SANTIAGO,,,"6,8",100,P,P
3515834,2004,25958,4,ESCUELA BASICA MIRASOL DE SANTIAGO,,2047,13,13101,SANTIAGO,4,...,19970709,0,13101,SANTIAGO,,,"6,8",98,P,P
3515835,2004,25958,4,ESCUELA BASICA MIRASOL DE SANTIAGO,,2047,13,13101,SANTIAGO,4,...,19971026,0,13101,SANTIAGO,,,"6,7",98,P,P
3515836,2004,25958,4,ESCUELA BASICA MIRASOL DE SANTIAGO,,2047,13,13101,SANTIAGO,4,...,19980319,0,13101,SANTIAGO,,,"6,5",98,P,P
3515837,2004,25958,4,ESCUELA BASICA MIRASOL DE SANTIAGO,,2047,13,13101,SANTIAGO,4,...,19970805,0,13101,SANTIAGO,,,"6,2",91,P,P

In [21]:
data2003= pd.read_csv("Rendimiento por estudiante 2003.csv", sep=';')
data2003

,AGNO,RBD,DGV_RBD,NOM_RBD,LET_RBD,NUM_RBD,COD_REG_RBD,COD_COM_RBD,NOM_COM_RBD,COD_DEPE,...,FEC_NAC_ALU,INT_ALU,COD_COM_ALU,NOM_COM_ALU,COD_SEC,COD_ESPE,PROM_GRAL,ASISTENCIA,SIT_FIN,SIT_FIN_R
0,2003,1,9,LICEO POLITECNICO,A,2,1,1201,ARICA,2,...,19880523,0,1201,ARICA,,,"5,6",95,P,P
1,2003,1,9,LICEO POLITECNICO,A,2,1,1201,ARICA,2,...,19860323,0,1201,ARICA,,,"5,7",85,P,P
2,2003,1,9,LICEO POLITECNICO,A,2,1,1201,ARICA,2,...,19850117,0,1201,ARICA,,,"5,2",93,P,P
3,2003,1,9,LICEO POLITECNICO,A,2,1,1201,ARICA,2,...,19740211,0,1201,ARICA,,,"5,7",94,P,P
4,2003,1,9,LICEO POLITECNICO,A,2,1,1201,ARICA,2,...,19870102,0,1201,ARICA,,,"5,6",98,P,P
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3528757,2003,25835,0,COLEGIO MANQUEHUE DE LAS CONDES,,,13,13114,LAS CONDES,4,...,19900922,0,13114,LAS CONDES,,,"6,3",90,P,P
3528758,2003,25835,0,COLEGIO MANQUEHUE DE LAS CONDES,,,13,13114,LAS CONDES,4,...,19860111,0,13114,LAS CONDES,,,"4,5",85,P,P
3528759,2003,25835,0,COLEGIO MANQUEHUE DE LAS CONDES,,,13,13114,LAS CONDES,4,...,19850812,0,13115,LO BARNECHEA,,,"4,5",85,P,P
3528760,2003,25835,0,COLEGIO MANQUEHUE DE LAS CONDES,,,13,13114,LAS CONDES,4,...,19951016,0,13114,LAS CONDES,,,"6,5",98,P,P
3528761,2003,25835,0,COLEGIO MANQUEHUE DE LAS CONDES,,,13,13114,LAS CONDES,4,...,19950403,0,13114,LAS CONDES,,,"6,3",95,P,P

In [22]:
data2002 = pd.read_csv("Rendimiento por estudiante 2002.csv", sep=';')
data2002

,AGNO,RBD,DGV_RBD,NOM_RBD,LET_RBD,NUM_RBD,COD_REG_RBD,COD_COM_RBD,NOM_COM_RBD,COD_DEPE,...,LET_CUR,MRUN,GEN_ALU,FEC_NAC_ALU,COD_COM_ALU,NOM_COM_ALU,PROM_GRAL,ASISTENCIA,SIT_FIN,SIT_FIN_R
0,2002,1,9,LICEO POLITECNICO,A,2,1,1201,ARICA,2,...,A,10081,1,Sep 16 1962,1201,ARICA,0,0,Y,Y
1,2002,1,9,LICEO POLITECNICO,A,2,1,1201,ARICA,2,...,F,13604,2,Jan 17 1985,1201,ARICA,"5,1",91,P,P
2,2002,1,9,LICEO POLITECNICO,A,2,1,1201,ARICA,2,...,A,20935,1,Feb 11 1974,1201,ARICA,6,99,P,P
3,2002,1,9,LICEO POLITECNICO,A,2,1,1201,ARICA,2,...,D,30441,1,Jan 2 1986,1201,ARICA,"5,6",97,P,P
4,2002,1,9,LICEO POLITECNICO,A,2,1,1201,ARICA,2,...,D,33767,1,Mar 26 1983,1201,ARICA,"6,5",85,P,P
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3376040,2002,25697,8,ESCUELA BASICA PARTICULAR O'HIGGINS,,115,13,13501,MELIPILLA,3,...,A,20245677,1,Jan 22 1996,13501,MELIPILLA,"6,5",100,P,P
3376041,2002,25697,8,ESCUELA BASICA PARTICULAR O'HIGGINS,,115,13,13501,MELIPILLA,3,...,A,21691106,2,Oct 18 1995,13501,MELIPILLA,"6,6",100,P,P
3376042,2002,25697,8,ESCUELA BASICA PARTICULAR O'HIGGINS,,115,13,13501,MELIPILLA,3,...,A,21999713,1,Apr 3 1996,13501,MELIPILLA,"6,8",100,P,P
3376043,2002,25697,8,ESCUELA BASICA PARTICULAR O'HIGGINS,,115,13,13501,MELIPILLA,3,...,A,22444776,1,Oct 14 1995,13501,MELIPILLA,"6,3",100,P,P
3376044,2002,25697,8,ESCUELA BASICA PARTICULAR O'HIGGINS,,115,13,13501,MELIPILLA,3,...,A,24878267,1,Sep 8 1995,13501,MELIPILLA,"6,8",100,P,P

In [23]:
# Suponiendo que los DataFrames están almacenados en una lista llamada data_list
data_list = [data2002, data2003, data2004, data2005, data2006, data2007,
             data2008, data2009, data2010, data2011, data2012, data2013,
             data2014, data2015, data2016, data2017, data2018, data2019,
             data2020, data2021, data2022]

In [ ]:
# Concatenar los DataFrames en un solo DataFrame
Rendimiento_200222 = pd.concat(data_list, axis=0)

In [ ]:
Rendimiento_200222 = pd.concat([data2002,data2003,data2004,data2005,data2006,data2007, data2008,data2009,data2010,data2011,data2012,data2013,data2014,data2015,data2016,data2017,data2018, data2019,data2020,data2021,data2022], axis=0)

In [ ]:
Rendimiento_200222 ['PROM_GRAL'] = Rendimiento_200222 (data['PROM_GRAL'],errors = 'coerce')

In [ ]:
data.describe()

In [ ]:
data.drop(['AGNO','DGV_RBD','COD_COM_RBD','MRUN','FEC_NAC_ALU','COD_TIP_CUR', "COD_REG_ALU", "COD_COM_ALU", "NOM_COM_ALU"], axis=1, inplace=True)
data.head()

In [ ]:
data.describe()

In [ ]:
CH2022= data[(data['COD_ENSE'] == 310) & (data["COD_DEPE"] == 3)& (data["COD_GRADO"] == 4)]

In [ ]:
CH2 = CH2022.loc[CH2022['COD_REG_RBD'].isin([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16])]

In [ ]:
CH2.info()

In [ ]:
regiones2022 = CH2.groupby('COD_REG_RBD')['PROM_GRAL'].mean().reset_index()

In [ ]:
regiones2022

In [ ]:
regiones2022.mean()

In [ ]:
regiones2022.median()

In [ ]:
fig= sns.catplot(data=regiones2022, x="COD_REG_RBD", y='PROM_GRAL', kind="point",height=6, aspect=1.6).set(title='Promedio de Notas Cuarto medio HC PS 2022 por regiones')

fig.refline(y=4.37, color='red')

plt.savefig("CH2018_600dpi.pdf", dpi=600)

In [ ]:
sns.boxplot(data=CH2, x="COD_REG_RBD", y="PROM_GRAL", dodge=False).set_title("X Notas IV medio PS 2022",
                  fontdict = {'fontsize': 16,
                              'fontweight': 'bold',
                              'color': 'blue'}) 


plt.show()

In [ ]:
CH2022PP= data[(data['COD_ENSE'] == 310) & (data["COD_DEPE"] == 4)& (data["COD_GRADO"] == 4)]

In [ ]:
CH2PP = CH2022PP.loc[CH2022PP['COD_REG_RBD'].isin([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16])]

In [ ]:
CH2PP.describe()

In [ ]:
regiones2022PP = CH2PP.groupby('COD_REG_RBD')['PROM_GRAL'].mean().reset_index()

In [ ]:
regiones2022PP

In [ ]:
regiones2022.mean()

In [ ]:
regiones2022.median()

In [ ]:
regiones2022.count()

In [ ]:
regiones2022PP = CH2PP.groupby('COD_REG_RBD')['PROM_GRAL'].mean().reset_index()

In [ ]:
regiones2022PP

In [ ]:
fig= sns.catplot(data=regiones2022PP, x="COD_REG_RBD", y='PROM_GRAL', kind="point",height=6, aspect=1.6).set(title='Promedio de Notas IVM HC PP 2022 por regiones')

fig.refline(y=4.37, color='red')

plt.savefig("CH2018_600dpi.pdf", dpi=600)

In [ ]:
sns.boxplot(data=CH2PP, x="COD_REG_RBD", y="PROM_GRAL", dodge=False).set_title("X Notas IV medio PP 2022",
                  fontdict = {'fontsize': 16,
                              'fontweight': 'bold',
                              'color': 'blue'}) 


plt.show()

In [ ]:
data[(data['COD_REG_RBD'] == 10)  & (data['COD_DEPROV_RBD'] == 101)]

In [ ]:
PPPMPV = data.loc[data['RBD'].isin([7700,7435,7717,22144,22506,7742])]

In [ ]:
PPPMPV

In [ ]:
PPPMPV.boxplot(by ='RBD', column =['PROM_GRAL'], grid = False, fontsize=12 )

plt.xlabel('Colegios',fontsize=16)

plt.ylabel('Notas',fontsize=16)

#plt.figure(figsize=(20,6))
plt.rcParams['figure.figsize'] = [12, 12]


plt.savefig("figura_300dpi.jpg", dpi=300)
plt.savefig("figura_600dpi.png", dpi=600)

plt.show()

In [ ]:
sns.boxplot(data=PPPMPV, x="RBD", y="PROM_GRAL", hue="RBD", dodge=False).set_title("Notas IV medio PP 2022",
                  fontdict = {'fontsize': 20,
                              'fontweight': 'bold',
                              'color': 'blue'}) 


plt.show()

In [ ]:
csfj= data[(data['COD_REG_RBD'] == 10)   &(data['RBD'] == 7717) & (data['COD_ENSE'] == 110) & (data["COD_GRADO"] == 3)]

In [ ]:
csfj.describe